name: attendance_app
description: University attendance system using facial recognition
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # State management
  provider: ^6.0.5
  # Network and storage
  http: ^1.4.0
  shared_preferences: ^2.2.0
  # UI
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  # Camera and ML
  camera: ^0.11.1
  google_mlkit_face_detection: ^0.13.1
  # Network connectivity
  connectivity_plus: ^6.1.4
  # Others
  intl: ^0.20.2
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  csv: ^6.0.0
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
